---
title: "Spherical abberation caused by ill-matched refractive indicies"
description: |
  When imaging a 3D volume in an aqueous solution using an oil objective your sample will be artificially and markedly squashed in z. Silicon and water objectives offer a much better solution. 
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Most immersion type objective lenses come in one of two varieties: oil or water. Oil has a refractive index (n) of approximately 1.515 and water n = 1.33. However, most living systems are composed of structures with refractive indices somewhere between these two values, with n ≈ 1.4 commonly cited as an estimate.

Why is it important to more closely match the refractive index of your sample? The primary answer is spherical aberration, which arises from refractive index mismatches occurring along the optical path, ultimately limiting imaging performance in samples of non-trivial thickness. To address this issue Nikon has committed to developing a selection of silicone immersion lenses for high performance live cell imaging. Silicone oil has n= 1.4, more closely approximating the cellular environment than oil or water.

The Lambda S 100XC Sil is an ideal lens for the highest resolution confocal and super-resolution applications. The Lambda S 25XC Sil and Lambda S 40XC Sil lenses also provide high resolution and minimize spherical aberration, but are designed for larger biological samples such as spheroids (image) and whole model organisms. These lenses feature an Optical Field Number of 25, providing the largest field of view in their class and optimal for high throughput imaging applications.

Additionally, these lenses feature a correction collar for further fine-tuning spherical aberration correction, including for experiments performed at 37oC. Evaporation of silicone oil is almost negligible, even at 37oC, making these lenses superior choices for long-term, time-lapse imaging experiments. As with other Lambda S objectives, the silicone immersion series features Nikon’s exclusive Nano Crystal Coat for maximizing transmittance.


