---
title: "May 2020 Twitter roundup"
categories:
  - Twitter posts
description: |
  Microsocpy based twitter posts that have caught my attention this month
draft: false
author:
  - name: Mark Rigby 
    affiliation: Nikon Insturments UK
    position: Advanced Imaging Specialist
    affiliation_url: https://www.microscope.healthcare.nikon.com/
preview: images/twitter_logo.PNG
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2


---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
library(twitterwidget)
library(knitr)

```


#### MesoSPIM version 5  


```{r twitter 1, layout="l-body"}

twitterwidget('1158687219223339008')

```
<br>
<br>
<br>
<br>
<br>

#### Effect of optical components to image and conjugate planes.  


```{r twitter 2, layout="l-body"}

twitterwidget('1265452074227163141')

```
<br>
<br>
<br>
<br>
<br>


####  Online tool for drawing optical schematics.  


```{r twitter 3, layout="l-body"}

twitterwidget('1255512265148727296')

```
<br>
<br>
<br>
<br>
<br>

#### Nikon small world 
Enteries for 2020 are now closed with the winners to be annoced 15th October  


```{r twitter 4, layout="l-body"}

twitterwidget('1263121194955485191')

```
<br>
<br>
<br>
<br>
<br>

#### Another useful reminder about MicroscopyU

```{r twitter 5, layout="l-body"}

twitterwidget('1266040899932471298')

```

#### Drosophila image awards 2020

```{r twitter 5, layout="l-body"}
twitterwidget('1266040105996697600')

```


#### Galvano mirrors

```{r twitter 5, layout="l-body"}

twitterwidget('1266376729464987648

```

#### Tips for what to include in you imaging methods section

```{r twitter 5, layout="l-body"}

twitterwidget('1266093328413724673

```




